name: Use a custom Action                                               
on: push                                                  
jobs:        
  use-your-own-action:
    name: Say Hi using your own action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        
      - uses: dmesquita/github-actions-tutorial@master
        with:
         user: 'DÃ©borah'
